select * from coupon;

INSERT INTO COUPON(COUPON_NAME, LOWER_RANGE, UPPER_RANGE, ACTIVITY_STATUS, DISCOUNT) 
VALUES('SILVER', 30, 50, 'ACTIVE', 0.1);

INSERT INTO COUPON(COUPON_NAME, LOWER_RANGE, UPPER_RANGE, ACTIVITY_STATUS, DISCOUNT) 
VALUES('GOLD', 50, 100, 'ACTIVE', 0.2);

INSERT INTO COUPON(COUPON_NAME, LOWER_RANGE, UPPER_RANGE, ACTIVITY_STATUS, DISCOUNT) 
VALUES('PLATINUM', 100, 150, 'ACTIVE', 0.3);
